### ISSUE TITLE
Not a Vue2 example

### ISSUE THREAD

**Issue by emahuni** [antfu/vueuse-vue2-example#2]
I thought this was supposed to be a Vue2 example, but it's not

**Comment by antfu** [comment]
What do you mean "not a Vue2 example"?

**Comment by emahuni** [comment]
I mean just that. Pure Vue 2 doesn't use composition API. I've a project that is strictly Vue 2 and I was expecting normal Vue single file component code in the example and the example isn't Vue 2, but 3. Please check what I mean and correct. You rock by the way.

**Comment by emahuni** [comment]
I can fiddle and write the correct syntax, but was just wondering how you'd envisioned the correct syntax as the author or maintainer since it's mentioned in the documentation that is seamless between Vue 2 and 3.

**Comment by antfu** [comment]
This is the example of [**using VueUse**](https://github.com/antfu/vueuse) with Vue 2. Not "general for Vue 2".

**Comment by emahuni** [comment]
?

**Comment by antfu** [comment]
!
